version: "3.1"
services:
  postgres:
    env_file: "./.env"
    image: postgres:9.6
    container_name: "postgres"
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      "POSTGRES_HOST": "${DB_HOST}"
      "POSTGRES_DB": "${DB_NAME}"
      "POSTGRES_USER": "${DB_USER}"
      "POSTGRES_PASSWORD": "${DB_PASSWORD}"
      "TZ": "GMT"
volumes: 
  postgresql-volume:
    external: true